project:
  type: book
  output-dir: docs

book:
  title: "Practicuanti"
  author: "Docentes Cuanti"
  chapters:
    - index.qmd
    - practico_2.qmd
    - practico_3.qmd
    - practico_4.qmd
    - practico_5.qmd
    - practico_6.qmd
    - practico_7.qmd
    - practico_8.qmd
    - practico_9.qmd
    - practico_10.qmd
    - practico_11.qmd
    - practico_12.qmd
    - entregable.qmd
 
format:
  html:
    theme: cosmo
    css: cuantistats.css
    number-sections: false
    toc: true
    toc-depth: 3
    number-depth: 2
    
resources:
  - descargables/**

editor: visual

execute:
  cache: true
  echo: false

